spring:
  config:
    import: "optional:env[.properties]"
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SERVER_PROTOCOL}://${SERVER_HOST}/login/oauth2/code/naver
            client-authentication-method: client_secret_post
            client-name: Naver
            scope: name,email,profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:lightblue-key.json
      project-id: ${PROJECT_ID}
gcp:
  bucket:
    name: ${GCP_BUCKET_NAME:lightblue-bucket}

logging:
  level:
    org.springframework.security: DEBUG
    com.example.lightblue: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # 24 hours

server:
  port: 8080

