spring:
  config:
    import: "optional:env[.properties]"
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  jackson:
    time-zone: Asia/Seoul
logging:
  level:
    org.springframework.security: DEBUG
    com.example.lightblue: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # 24 hours

server:
  port: 8080
